sudo: false
language: python
python:
  - "2.7.6"
install: python setup.py -q install
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - pip install -r requirements.txt
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate --noinput
  - npm install mocha
  - npm install jquery
  - npm install jsdom@3
script:
  - pep8 scout_manager/ --exclude=migrations,scout_manager/test
  - coverage run --source=scout_manager/ --omit=scout_manager/migrations/* manage.py test scout_manager
after_script:
  - coveralls
notifications:
#  slack:
# TODO generate new slack key
#        secure: QhQcPJdxvdl5GlPdiewvyMMzDAM5fFB0Db2kRwpDphn8KiyNv2cF1SVeiYaJcQ4fObA7eWgsBXGBd/be8OC/1ujGNncz92bJM5xHePzMxs37hjPFaHuDGH0pnqurQIhRTz6OoWDi2+2OzC3xP1VkpOv0/2ApFjhUkO8S6JodH9A=
